# Site settings
title: Munkhod's page
description: Welcome to my personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Munkhod Bayarsaikhan
<<<<<<< HEAD
user_description: Welcome to my personal page!
user_title: Graduate Student of CS
email: munkhod.bayar@gmail.com
=======
user_description: Welcome to my personal page. I will share my everything to you!
user_title: Graduate Student of Engineering
email: munju08@gmail.com
>>>>>>> c9696e7a94b49f008a7098d1f2b2218fcb82a0bd
facebook_username: munjuub
twitter_username: MunjuuB
github_username:  munjuu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
